# Generated by Django 3.1.5 on 2021-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorArcana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name_pt', models.CharField(max_length=50)),
                ('card_name_fr', models.CharField(default='Arcane', max_length=50)),
                ('card_name_es', models.CharField(default='Arcane', max_length=50)),
                ('card_name_en', models.CharField(default='Arcane', max_length=50)),
                ('card_signification_gen_pt', models.TextField()),
                ('card_signification_gen_fr', models.TextField(default='gen')),
                ('card_signification_gen_es', models.TextField(default='gen')),
                ('card_signification_gen_en', models.TextField(default='gen')),
                ('card_signification_warnings_pt', models.TextField()),
                ('card_signification_warnings_fr', models.TextField(default='warning')),
                ('card_signification_warnings_es', models.TextField(default='warning')),
                ('card_signification_warnings_en', models.TextField(default='warning')),
                ('card_signification_love_pt', models.TextField()),
                ('card_signification_love_fr', models.TextField(default='love')),
                ('card_signification_love_es', models.TextField(default='love')),
                ('card_signification_love_en', models.TextField(default='love')),
                ('card_signification_work_pt', models.TextField()),
                ('card_signification_work_fr', models.TextField(default='work')),
                ('card_signification_work_es', models.TextField(default='work')),
                ('card_signification_work_en', models.TextField(default='work')),
                ('card_image', models.CharField(max_length=100)),
                ('card_polarity', models.CharField(choices=[('Positif', 'Positif'), ('Negatif', 'Negatif'), ('Neutral', 'neutral')], default='Positif', max_length=10)),
            ],
        ),
    ]
