# Generated by Django 3.1.5 on 2021-02-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairvoyance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majorarcana',
            old_name='card_signification_gen',
            new_name='card_signification_gen_pt',
        ),
        migrations.RenameField(
            model_name='majorarcana',
            old_name='card_signification_love',
            new_name='card_signification_love_pt',
        ),
        migrations.RenameField(
            model_name='majorarcana',
            old_name='card_signification_warnings',
            new_name='card_signification_warnings_pt',
        ),
        migrations.RenameField(
            model_name='majorarcana',
            old_name='card_signification_work',
            new_name='card_signification_work_pt',
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_name_fr',
            field=models.CharField(default='Arcane', max_length=50),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_gen_fr',
            field=models.TextField(default='gen'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_love_fr',
            field=models.TextField(default='love'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_warnings_fr',
            field=models.TextField(default='warning'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_work_fr',
            field=models.TextField(default='work'),
        ),
    ]
