# Generated by Django 3.0.7 on 2020-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairvoyance', '0002_majorarcana_card_palarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorarcana',
            name='card_palarity',
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_polarity',
            field=models.CharField(choices=[('Positif', 'Positif'), ('Negatif', 'Negatif'), (
                'Neutral', 'neutral')], default='Positif', max_length=10),
        ),
    ]
