# Generated by Django 3.1.5 on 2021-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairvoyance', '0002_auto_20210206_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorarcana',
            name='card_name_en',
            field=models.CharField(default='Arcane', max_length=50),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_name_es',
            field=models.CharField(default='Arcane', max_length=50),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_gen_en',
            field=models.TextField(default='gen'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_gen_es',
            field=models.TextField(default='gen'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_love_en',
            field=models.TextField(default='love'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_love_es',
            field=models.TextField(default='love'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_warnings_en',
            field=models.TextField(default='warning'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_warnings_es',
            field=models.TextField(default='warning'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_work_en',
            field=models.TextField(default='work'),
        ),
        migrations.AddField(
            model_name='majorarcana',
            name='card_signification_work_es',
            field=models.TextField(default='work'),
        ),
    ]
