# Generated by Django 3.1.5 on 2021-02-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball8', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='sentence_en',
            field=models.CharField(default='sentence_en', max_length=200),
        ),
        migrations.AddField(
            model_name='sentences',
            name='sentence_es',
            field=models.CharField(default='sentence_es', max_length=200),
        ),
        migrations.AddField(
            model_name='sentences',
            name='sentence_fr',
            field=models.CharField(default='sentence_fr', max_length=200),
        ),
    ]
