# Generated by Django 3.2.4 on 2021-06-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ball8', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentences',
            old_name='sentence',
            new_name='sentence_pt',
        ),
    ]
