# Generated by Django 3.2.4 on 2021-06-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ball8', '0002_rename_sentence_sentences_sentence_pt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentences',
            old_name='sentence_pt',
            new_name='sentence',
        ),
    ]
