# Generated by Django 3.1.5 on 2021-02-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ball8', '0002_auto_20210222_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='sentence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='sentence_en',
            field=models.TextField(default='sentence_en'),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='sentence_es',
            field=models.TextField(default='sentence_es'),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='sentence_fr',
            field=models.TextField(default='sentence_fr'),
        ),
    ]
