# Generated by Django 3.1.5 on 2021-02-08 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210207_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='daily_sorted_cards',
            field=models.CharField(default='list of cards', max_length=200),
        ),
        migrations.AddField(
            model_name='history',
            name='sorted_cards',
            field=models.CharField(default='list of sorted cards', max_length=100),
        ),
        migrations.AddField(
            model_name='history',
            name='sorted_cards_date',
            field=models.DateField(auto_created=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Utilizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
    ]
