# Generated by Django 3.1.5 on 2021-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairvoyance', '0003_auto_20210216_1648'),
        ('accounts', '0004_customuser_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='sorted_cards',
        ),
        migrations.AddField(
            model_name='history',
            name='sorted_cards',
            field=models.ManyToManyField(to='clairvoyance.MajorArcana', verbose_name='Tiragem'),
        ),
    ]
